### ISSUE TITLE
Http query params get messed up when they contain non-ascii chars (such as Č)

### ISSUE THREAD

**Issue by SoptikHa2** [rikulo/stream#84]
For example there is get request

`example.com/subject/Čj`

Routing:
`"get:/subject/(identifier:[^/]*)" : Subject.getSubject,`

When I get `connect.dataset['identifier']`, I assume it should have something like `Čj`, but instead, there is `%C4%8Cj`. How can I decode it, or, even better, can we get the real value there instead?

**Comment by tomyeh** [comment]
Please use `Uri.decodeComponent` to get it back.
